controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authentication_token:
    path: /authentication_token
    methods: ['POST']

authentication_refresh_token:
    path: /authentication_refresh_token
    methods: ['POST']